config/routes.rb
Rails.application.routes.draw do

	root to: "personal_goals#index"

	resources :personal_goal_trackers
	resources :users
	resources :personal_goals


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal_goal.rb
class PersonalGoal < ApplicationRecord
  belongs_to :user
  has_many :personal_goal_trackers

  validates_presence_of :name, :type_of_outcome, :target 

  def progress
  	if self.measured_by = "decrease"
  		self.progress = (self.personal_goal_trackers.first.record_amount) - (self.personal_goal_trackers.last.record_amount)
  	elsif self.measured_by = "increase" 
  		self.progress = (self.personal_goal_trackers.last.record_amount) - (self.personal_goal_trackers.first.record_amount)
  	elsif self.measured_by = "maintain"
  		self.progress = (self.personal_goal.target) - (self.personal_goal_trackers.last.record_amount)
  	elsif self.measured_by = "eliminate"
  		self.progress = self.personal_goal_trackers.last.record_amount
		end
  end

  def progress_in_percent
  	@progress_in_percent = (((self.progress.to_f)/(self.target))*100).round
  end
end

app/models/personal_goal_tracker.rb
class PersonalGoalTracker < ApplicationRecord
	belongs_to :personal_goal
end

app/models/user.rb
class User < ApplicationRecord
	has_many :personal_goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/personal_goal_trackers.rb
class PersonalGoalTrackersController < ApplicationController
	before_action :set_personal_goal_tracker, only: [:show, :edit, :update, :destroy]

	def index 
		@personal_goal_trackers = PersonalGoalTracker.all
	end

	def show
	end

	def new
		
	end

	def create

	end

	private
	def set_personal_goal_tracker
		@personal_goal_tracker = PersonalGoalTracker.find(params[:id])
	end
	def personal_goal_tracker_params 
		params.require(:personal_goal_trackers).permit(:personal_goal_id, :record_amount
	end

end

app/controllers/personal_goals_controller.rb
class PersonalGoalsController < ApplicationController
	before_action :set_personal_goal, only: [:show, :edit, :update, :destroy]

	def index 
		@personal_goals = PersonalGoal.all
	end

	def show
	end

	private
	def set_personal_goal
		@personal_goal = PersonalGoal.find(params[:id])
	end
	def personal_goal_params 
		params.require(:personal_goal).permit(:name, :user_name, :type_of_outcome, :target, :measured_by)
	end

end

app/controllers/users.controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index 
		@users = User.all
	end

	def show
	end

	private
	def set_user
		@user = User.find(params[:id])
	end
	def user_params 
		params.require(:user).permit(:name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Day2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/personal_goals/index.html.erb
<h1> Personal Goals </h1>
<div id = "personal_goals"> 
	<% @personal_goals.each do |personal_goal| %>
	<h2> 
		<%= link_to personal_goal.name, personal_goal %>
			<span class="personal_goals">(<%= pluralize(personal_goal.personal_goal_trackers.size, 'personal_goal_tracker') %>)</span>
	</h2>
	<div class="info">
		Recorded on: <%= personal_goal.created_at.strftime("%a, %b %d")%> 
		Goal: <%= personal_goal.type_of_outcome %> Target: <%= personal_goal.target %><%= personal_goal.measured_by %>
		Progress: "coming soon"
	</div>
	<% end %>
</div>

app/views/personal_goals/show.html.erb
<h1><%= @personal_goal.name.titleize %></h1>

<p class="user"><em> <%= @personal_goal.user.name %>'s Goal</em></p>


<div class="info">
    Recorded on: <%= @personal_goal.created_at.strftime("%a, %b %d")%> 
    Target: <%= @personal_goal.target %><%= @personal_goal.measured_by.pluralize %>
    <br>
    Progress: <%= @personal_goal.progress %>  That is 
    <%= @personal_goal.progress_in_percent %> %
</div>

<p><%= link_to "Back to personal_goals", personal_goals_path %></p>

<% unless @personal_goal.personal_goal_trackers.empty? %>
  <h2><%= @personal_goal.personal_goal_trackers.size %> records tracked </h2>

  <div id="personal_goal_trackers">
  <% for @personal_goal_tracker in @personal_goal.personal_goal_trackers %>
    <div class="personal_goal_tracker">
      <strong><%= @personal_goal_tracker.record_amount %> </strong>
      <em>on <%= @personal_goal_tracker.created_at.strftime("%a, %b %d")%></em>
      
    </div>
  <% end %>
  </div>
<% end %>